CREATE PROCEDURE [dbo].[uspConsultoriasUpdate]
(
    @id As uniqueidentifier,
	@nombre As varchar(100), 
	@usuarioRedGerente As varchar(50),
	@usuarioRedConsultor As varchar(50),
    @idLineaConsultoria As tinyint,
	@idLineaNegocio As tinyint,
    @idEstado As tinyint,
    @idOficina As tinyint,
    @idCliente As int,
	@idPais As tinyint,
    @urlDocumentacion As varchar(255),
    @urlDiseno As varchar(255),
    @urlGestionTareas As varchar(255),
    @urlGestionIncidentes As varchar(255),
    @urlGestionAseguramientoCalidad As varchar(255),
    @urlLeccionesAprendidas As varchar(255),
    @urlOportunidadCrm As varchar(255),
    @urlProyectoPsa As varchar(255),
    @nombreContactoCliente As varchar(100),
    @correoContactoCliente As varchar(70),
    @telefonoContactoCliente As varchar(12),
	@usuarioRedCreacionModificacion As varchar(50),
	@observacion As varchar(2000),
	@descripcion As varchar(2000),
    @fechaCreacion As datetime,
    @fechaCierre As datetime,
    @etiqueta As Varchar(5000),
    @horasEstimadas As int,
    @horasEjecutadas As int,
	@idUsosComerciales as tinyint,
	@objetivoNegocio as Int
)
AS
    UPDATE [dbo].[Consultoria]
   SET Nombre = @nombre,
       UsuarioRedGerente = @usuarioRedGerente,
       UsuarioRedConsultor = @usuarioRedConsultor,
       IdLineaConsultoria = @idLineaConsultoria, 
	   IdLineaNegocio = @idLineaNegocio,
       IdEstado = @idEstado, 
       IdOficina = @idOficina, 
       IdCliente = @idCliente, 
	   IdPais = @idPais,
       UrlDocumentacion = @urlDocumentacion,
       UrlDiseno = @urlDiseno,
       UrlGestionTareas = @urlGestionTareas,
       UrlGestionIncidentes = @urlGestionIncidentes,
       UrlGestionAseguramientoCalidad = @urlGestionAseguramientoCalidad,
       UrlLeccionesAprendidas = @urlLeccionesAprendidas,
       UrlOportunidadCrm = @urlOportunidadCrm,
       UrlProyectoPsa = @urlProyectoPsa,
       NombreContactoCliente = @nombreContactoCliente, 
       CorreoContactoCliente = @correoContactoCliente, 
       TelefonoContactoCliente = @telefonoContactoCliente,
	   FechaCreacionModificacion = getdate(),
	   UsuarioRedCreacionModificacion = @usuarioRedCreacionModificacion,
	   Observacion = @observacion,
	   Descripcion = @descripcion,
       FechaCreacion = @fechaCreacion,
       FechaCierre = @fechaCierre,
       Etiqueta = @etiqueta,
       HorasEstimadas = @horasEstimadas,
       HorasEjecutadas = @horasEjecutadas,
	   IdUsosComerciales = @idUsosComerciales,
	   ObjetivoNegocio = @objetivoNegocio
WHERE Id = @id
