CREATE PROCEDURE [dbo].[uspConsultoriasInsert] 
	
@id As uniqueidentifier,
	@nombre As varchar(100), 
	@usuarioRedGerente As varchar(50),
	@usuarioRedConsultor As varchar(50),
    @idLineaConsultoria As tinyint,
	@idLineaNegocio As tinyint,
    @idEstado As tinyint,
    @idOficina As tinyint,
    @idCliente As int,
	@idPais As tinyint,
    @urlDocumentacion As varchar(255),
    @urlDiseno As varchar(255),
    @urlGestionTareas As varchar(255),
    @urlGestionIncidentes As varchar(255),
    @urlGestionAseguramientoCalidad As varchar(255),
    @urlLeccionesAprendidas As varchar(255),
    @urlOportunidadCrm As varchar(255),
    @urlProyectoPsa As varchar(255),
    @nombreContactoCliente As varchar(100),
    @correoContactoCliente As varchar(70),
    @telefonoContactoCliente As varchar(12),
	@usuarioRedCreacionModificacion As varchar(50),
	@observacion As Varchar(2000),
	@descripcion As Varchar(2000),
    @fechaCreacion AS datetime,
    @fechaCierre As datetime,
    @etiqueta As Varchar(5000),
    @horasEstimadas As int,
    @horasEjecutadas as int,
	@idUsosComerciales as tinyint,
	@objetivoNegocio as int
AS

INSERT INTO dbo.Consultoria
           (Id,
		   Nombre,
           UsuarioRedGerente,
           UsuarioRedConsultor,
           IdLineaConsultoria,
		   IdLineaNegocio,
           IdEstado,
           IdOficina,
           IdCliente,
		   IdPais,
           UrlDocumentacion,
           UrlDiseno,
           UrlGestionTareas,
           UrlGestionIncidentes,
           UrlGestionAseguramientoCalidad,
           UrlLeccionesAprendidas,
           UrlOportunidadCrm,
           UrlProyectoPsa,
           NombreContactoCliente,
           CorreoContactoCliente,
           TelefonoContactoCliente,
		   FechaCreacionModificacion,
		   UsuarioRedCreacionModificacion,
		   Observacion,
		   Descripcion,
           FechaCreacion,
           FechaCierre,
           Etiqueta,
           HorasEstimadas,
           HorasEjecutadas,
		   IdUsosComerciales,
		   ObjetivoNegocio
		   )
     VALUES
           (@id,
           @nombre, 
           @usuarioRedGerente,
           @usuarioRedConsultor, 
           @idLineaConsultoria, 
		   @idLineaNegocio,
           @idEstado, 
           @idOficina, 
           @idCliente, 
		   @idPais,
           @urlDocumentacion,
           @urlDiseno,
           @urlGestionTareas,
           @urlGestionIncidentes,
           @urlGestionAseguramientoCalidad,
           @urlLeccionesAprendidas,
           @urlOportunidadCrm,
           @urlProyectoPsa,
           @nombreContactoCliente, 
           @correoContactoCliente, 
           @telefonoContactoCliente,
		   GETDATE(),
		   @usuarioRedCreacionModificacion,
		   @observacion,
		   @descripcion,
           @fechaCreacion,
           @fechaCierre,
           @etiqueta,
           @horasEstimadas,
           @horasEjecutadas,
		   @idUsosComerciales,
		   @objetivoNegocio
		   )
GO
