CREATE PROCEDURE [dbo].[uspSolucionesInsert]

    @id AS UNIQUEIDENTIFIER,
	@nombre AS VARCHAR(100), 
	@usuarioRedGerente AS VARCHAR(50),
	@usuarioRedResponsable AS VARCHAR(50),
    @usuarioRedScrumMASter AS VARCHAR(50),
	@idTipo AS TINYINT,
	@idMarcoTrabajo AS TINYINT,
    @idLineaSolucion AS TINYINT,
	@idLineaNegocio AS TINYINT,
    @idEstado AS TINYINT,
    @idOficina AS TINYINT,
    @idCliente AS INT,
	@idPais AS TINYINT,
    @urlRepositorioCodigoFuente AS VARCHAR(255),
    @urlDocumentacion AS VARCHAR(255),
    @urlInspeccion AS VARCHAR(255),
    @urlDiseno AS VARCHAR(255),
    @urlGestionTareAS AS VARCHAR(255),
    @urlGestionIncidentes AS VARCHAR(255),
    @urlGestionASeguramientoCalidad AS VARCHAR(255),
    @urlLeccionesAprendidAS AS VARCHAR(255),
    @urlOportunidadCrm AS VARCHAR(255),
    @urlProyectoPsa AS VARCHAR(255),
    @nombreContactoCliente AS VARCHAR(100),
    @correoContactoCliente AS VARCHAR(70),
    @telefonoContactoCliente AS VARCHAR(12),
	@usuarioRedCreacionModificacion AS VARCHAR(50),
	@observacion AS VARCHAR(2000),
	@descripcion AS VARCHAR(2000),
    @fechaCreacion AS DATETIME,
    @fechaCierre AS DATETIME,
    @experienciaUsuario AS BIT,
    @etiqueta AS VARCHAR(5000),
    @horASEstimadAS AS INT,
    @horASEjecutadAS AS INT,
	@idUsosComerciales AS TINYINT,
    @idConsultoria AS UNIQUEIDENTIFIER,
	@objetivoNegocio AS INT

    AS
    BEGIN
        INSERT INTO dbo.Soluciones
        (
            Id,
		    Nombre,
            UsuarioRedGerente,
            UsuarioRedResponsable,
            UsuarioRedScrumMASter,
            IdTipo,
            IdMarcoTrabajo,
            IdLineaSolucion,
		    IdLineaNegocio,
            IdEstado,
            IdOficina,
            IdCliente,
		    IdPais,
            UrlRepositorioCodigoFuente,
            UrlDocumentacion,
            UrlInspeccion,
            UrlDiseno,
            UrlGestionTareAS,
            UrlGestionIncidentes,
            UrlGestionASeguramientoCalidad,
            UrlLeccionesAprendidAS,
            UrlOportunidadCrm,
            UrlProyectoPsa,
            NombreContactoCliente,
            CorreoContactoCliente,
            TelefonoContactoCliente,
		    FechaCreacionModificacion,
		    UsuarioRedCreacionModificacion,
		    Observacion,
		    Descripcion,
            FechaCreacion,
            FechaCierre,
            ExperienciaUsuario,
            Etiqueta,
            HorASEstimadAS,
            HorASEjecutadAS,
		    IdUsosComerciales,
            IdConsultoria,
			ObjetivoNegocio
        )
        VALUES
        (
            @id,
            @nombre, 
            @usuarioRedGerente,
            @usuarioRedResponsable, 
            @usuarioRedScrumMASter,
            @idTipo, 
            @idMarcoTrabajo, 
            @idLineaSolucion, 
		    @idLineaNegocio,
            @idEstado, 
            @idOficina, 
            @idCliente, 
		    @idPais,
            @urlRepositorioCodigoFuente, 
            @urlDocumentacion, 
            @urlInspeccion,
            @urlDiseno,
            @urlGestionTareAS,
            @urlGestionIncidentes,
            @urlGestionASeguramientoCalidad,
            @urlLeccionesAprendidAS,
            @urlOportunidadCrm,
            @urlProyectoPsa,
            @nombreContactoCliente, 
            @correoContactoCliente, 
            @telefonoContactoCliente,
		    GETDATE(),
		    @usuarioRedCreacionModificacion,
		    @observacion,
		    @descripcion,
            @fechaCreacion,
            @fechaCierre,
            @experienciaUsuario,
            @etiqueta,
            @horASEstimadAS,
            @horASEjecutadAS,
		    @idUsosComerciales,
            @idConsultoria,
			@objetivoNegocio
        )
    END
GO
