CREATE PROCEDURE [dbo].[uspSolucionesUpdate]
(
    @id AS UNIQUEIDENTIFIER,
	@nombre AS VARCHAR(100), 
	@usuarioRedGerente AS VARCHAR(50),
	@usuarioRedResponsable AS VARCHAR(50),
    @usuarioRedScrumMaster AS VARCHAR(50),
	@idTipo AS TINYINT,
	@idMarcoTrabajo AS TINYINT,
    @idLineaSolucion AS TINYINT,
	@idLineaNegocio AS TINYINT,
    @idEstado AS TINYINT,
    @idOficina AS TINYINT,
    @idCliente AS INT,
	@idPais AS TINYINT,
    @urlRepositorioCodigoFuente AS VARCHAR(255),
    @urlDocumentacion AS VARCHAR(255),
    @urlInspeccion AS VARCHAR(255),
    @urlDiseno AS VARCHAR(255),
    @urlGestionTareas AS VARCHAR(255),
    @urlGestionIncidentes AS VARCHAR(255),
    @urlGestionAseguramientoCalidad AS VARCHAR(255),
    @urlLeccionesAprendidas AS VARCHAR(255),
    @urlOportunidadCrm AS VARCHAR(255),
    @urlProyectoPsa  AS VARCHAR(255),
    @nombreContactoCliente AS VARCHAR(100),
    @correoContactoCliente AS VARCHAR(70),
    @telefonoContactoCliente AS VARCHAR(12),
	@usuarioRedCreacionModificacion AS VARCHAR(50),
	@observacion AS VARCHAR(2000),
	@descripcion AS VARCHAR(2000),
    @fechaCreacion AS DATETIME,
    @fechaCierre AS DATETIME,
    @experienciaUsuario AS BIT,
    @etiqueta AS VARCHAR(5000),
    @horasEstimadas AS INT,
    @horasEjecutadas AS INT,
	@idUsosComerciales AS TINYINT,
    @idConsultoria AS UNIQUEIDENTIFIER,
	@objetivoNegocio AS INT
)

    AS
    BEGIN
        UPDATE [dbo].[Soluciones]
        SET 
            Nombre = @nombre,
            UsuarioRedGerente = @usuarioRedGerente,
            UsuarioRedResponsable = @usuarioRedResponsable,
            UsuarioRedScrumMaster = @usuarioRedScrumMaster,
            IdTipo = @idTipo,
            IdMarcoTrabajo = @idMarcoTrabajo,
            IdLineaSolucion = @idLineaSolucion, 
	        IdLineaNegocio = @idLineaNegocio,
            IdEstado = @idEstado, 
            IdOficina = @idOficina, 
            IdCliente = @idCliente, 
	        IdPais = @idPais,
            UrlRepositorioCodigoFuente = @urlRepositorioCodigoFuente, 
            UrlDocumentacion = @urlDocumentacion, 
            UrlInspeccion = @urlInspeccion,
            UrlDiseno = @urlDiseno,
            UrlGestionTareas = @urlGestionTareas,
            UrlGestionIncidentes = @urlGestionIncidentes,
            UrlGestionAseguramientoCalidad = @urlGestionAseguramientoCalidad,
            UrlLeccionesAprendidas = @urlLeccionesAprendidas,
            UrlOportunidadCrm = @urlOportunidadCrm,
            UrlProyectoPsa = @urlProyectoPsa,
            NombreContactoCliente = @nombreContactoCliente, 
            CorreoContactoCliente = @correoContactoCliente, 
            TelefonoContactoCliente = @telefonoContactoCliente,
	        FechaCreacionModificacion = GETDATE(),
	        UsuarioRedCreacionModificacion = @usuarioRedCreacionModificacion,
	        Observacion = @observacion,
	        Descripcion = @descripcion,
            FechaCreacion = @fechaCreacion,
            FechaCierre = @fechaCierre,
            ExperienciaUsuario = @experienciaUsuario,
            Etiqueta = @etiqueta,
            HorasEstimadas = @horasEstimadas,
            HorasEjecutadas = @horasEjecutadas,
	        IdUsosComerciales = @idUsosComerciales,
            IdConsultoria = @idConsultoria,
			ObjetivoNegocio = @objetivoNegocio
        WHERE Id = @id
    END
GO
