//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lenguaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Varo.Web.Resources.Lenguaje", typeof(Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abiertos.
        /// </summary>
        public static string Abiertos {
            get {
                return ResourceManager.GetString("Abiertos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC.
        /// </summary>
        public static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        public static string Acción {
            get {
                return ResourceManager.GetString("Acción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones de Mejora.
        /// </summary>
        public static string AccionesMejora {
            get {
                return ResourceManager.GetString("AccionesMejora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción de Mejora.
        /// </summary>
        public static string AcciónMejora {
            get {
                return ResourceManager.GetString("AcciónMejora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuales.
        /// </summary>
        public static string Actuales {
            get {
                return ResourceManager.GetString("Actuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar.
        /// </summary>
        public static string Administrar {
            get {
                return ResourceManager.GetString("Administrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Solución.
        /// </summary>
        public static string AdministrarSolución {
            get {
                return ResourceManager.GetString("AdministrarSolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar consultoría.
        /// </summary>
        public static string AgregarConsultoria {
            get {
                return ResourceManager.GetString("AgregarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar solución.
        /// </summary>
        public static string AgregarSolución {
            get {
                return ResourceManager.GetString("AgregarSolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        public static string Año {
            get {
                return ResourceManager.GetString("Año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string Auditoria {
            get {
                return ResourceManager.GetString("Auditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditorias.
        /// </summary>
        public static string Auditorias {
            get {
                return ResourceManager.GetString("Auditorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs.
        /// </summary>
        public static string Bugs {
            get {
                return ResourceManager.GetString("Bugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar consultoría.
        /// </summary>
        public static string BuscarConsultoria {
            get {
                return ResourceManager.GetString("BuscarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar solucion.
        /// </summary>
        public static string BuscarSolucion {
            get {
                return ResourceManager.GetString("BuscarSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar solución.
        /// </summary>
        public static string Buscarsolución {
            get {
                return ResourceManager.GetString("Buscarsolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros..
        /// </summary>
        public static string BusquedaSinRegistro {
            get {
                return ResourceManager.GetString("BusquedaSinRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad de Código.
        /// </summary>
        public static string CalidaddeCódigo {
            get {
                return ResourceManager.GetString("CalidaddeCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad del Código.
        /// </summary>
        public static string CalidaddelCódigo {
            get {
                return ResourceManager.GetString("CalidaddelCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificacion.
        /// </summary>
        public static string Calificacion {
            get {
                return ResourceManager.GetString("Calificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación.
        /// </summary>
        public static string Calificación {
            get {
                return ResourceManager.GetString("Calificación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación Auditoría.
        /// </summary>
        public static string CalificaciónAuditoría {
            get {
                return ResourceManager.GetString("CalificaciónAuditoría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación de Auditoría.
        /// </summary>
        public static string CalificacióndeAuditoría {
            get {
                return ResourceManager.GetString("CalificacióndeAuditoría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación de Desempeño.
        /// </summary>
        public static string CalificacióndeDesempeño {
            get {
                return ResourceManager.GetString("CalificacióndeDesempeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación de Seguridad.
        /// </summary>
        public static string CalificacióndeSeguridad {
            get {
                return ResourceManager.GetString("CalificacióndeSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación Desempeño.
        /// </summary>
        public static string CalificaciónDesempeño {
            get {
                return ResourceManager.GetString("CalificaciónDesempeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación Seguridad.
        /// </summary>
        public static string CalificaciónSeguridad {
            get {
                return ResourceManager.GetString("CalificaciónSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de idioma.
        /// </summary>
        public static string Cambiodeidioma {
            get {
                return ResourceManager.GetString("Cambiodeidioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        public static string Cargando {
            get {
                return ResourceManager.GetString("Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casos a automatizar.
        /// </summary>
        public static string CasosaAutomatizar {
            get {
                return ResourceManager.GetString("CasosaAutomatizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casos automatizados.
        /// </summary>
        public static string CasosAutomatizados {
            get {
                return ResourceManager.GetString("CasosAutomatizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casos definidos.
        /// </summary>
        public static string CasosDefinidos {
            get {
                return ResourceManager.GetString("CasosDefinidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrados.
        /// </summary>
        public static string Cerrados {
            get {
                return ResourceManager.GetString("Cerrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ciudad {
            get {
                return ResourceManager.GetString("Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura.
        /// </summary>
        public static string Cobertura {
            get {
                return ResourceManager.GetString("Cobertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code smell.
        /// </summary>
        public static string Codesmell {
            get {
                return ResourceManager.GetString("Codesmell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código duplicado.
        /// </summary>
        public static string Códigoduplicado {
            get {
                return ResourceManager.GetString("Códigoduplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compromisos.
        /// </summary>
        public static string Compromisos {
            get {
                return ResourceManager.GetString("Compromisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultor.
        /// </summary>
        public static string Consultor {
            get {
                return ResourceManager.GetString("Consultor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultorías.
        /// </summary>
        public static string Consultoria {
            get {
                return ResourceManager.GetString("Consultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su consultoria ha sido.
        /// </summary>
        public static string ConsultoriaHaSido {
            get {
                return ResourceManager.GetString("ConsultoriaHaSido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultorias.
        /// </summary>
        public static string Consultorias {
            get {
                return ResourceManager.GetString("Consultorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string Continuar {
            get {
                return ResourceManager.GetString("Continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de código.
        /// </summary>
        public static string Controldecódigo {
            get {
                return ResourceManager.GetString("Controldecódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control de documentación.
        /// </summary>
        public static string Controldedocumentación {
            get {
                return ResourceManager.GetString("Controldedocumentación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creado.
        /// </summary>
        public static string creado {
            get {
                return ResourceManager.GetString("creado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumple.
        /// </summary>
        public static string Cumple {
            get {
                return ResourceManager.GetString("Cumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defectos Externos.
        /// </summary>
        public static string DefectosExternos {
            get {
                return ResourceManager.GetString("DefectosExternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defectos Internos.
        /// </summary>
        public static string DefectosInternos {
            get {
                return ResourceManager.GetString("DefectosInternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Densidad.
        /// </summary>
        public static string Densidad {
            get {
                return ResourceManager.GetString("Densidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripción {
            get {
                return ResourceManager.GetString("Descripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desempeño.
        /// </summary>
        public static string Desempeño {
            get {
                return ResourceManager.GetString("Desempeño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despliegue continuo.
        /// </summary>
        public static string Desplieguecontinuo {
            get {
                return ResourceManager.GetString("Desplieguecontinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despliegues Continuos.
        /// </summary>
        public static string Desplieguescontinuos {
            get {
                return ResourceManager.GetString("Desplieguescontinuos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Historias de Usuario.
        /// </summary>
        public static string DetalledeHistoriasdeUsuario {
            get {
                return ResourceManager.GetString("DetalledeHistoriasdeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuda técnica.
        /// </summary>
        public static string Deudatécnica {
            get {
                return ResourceManager.GetString("Deudatécnica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs / Cod.
        /// </summary>
        public static string DocsCod {
            get {
                return ResourceManager.GetString("DocsCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicado.
        /// </summary>
        public static string Duplicado {
            get {
                return ResourceManager.GetString("Duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Solución.
        /// </summary>
        public static string EditarSolución {
            get {
                return ResourceManager.GetString("EditarSolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo Estimado.
        /// </summary>
        public static string EsfuerzoEstimado {
            get {
                return ResourceManager.GetString("EsfuerzoEstimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo Estimados.
        /// </summary>
        public static string EsfuerzoEstimados {
            get {
                return ResourceManager.GetString("EsfuerzoEstimados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo Logrados.
        /// </summary>
        public static string EsfuerzoLogrados {
            get {
                return ResourceManager.GetString("EsfuerzoLogrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esfuerzo Real.
        /// </summary>
        public static string EsfuerzoReal {
            get {
                return ResourceManager.GetString("EsfuerzoReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estabilidad.
        /// </summary>
        public static string Estabilidad {
            get {
                return ResourceManager.GetString("Estabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado actual de las soluciones.
        /// </summary>
        public static string Estadoactualdelassoluciones {
            get {
                return ResourceManager.GetString("Estadoactualdelassoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Esta en el pipeline del CD?.
        /// </summary>
        public static string EstaenPipeline {
            get {
                return ResourceManager.GetString("EstaenPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquetas.
        /// </summary>
        public static string Etiquetas {
            get {
                return ResourceManager.GetString("Etiquetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelente.
        /// </summary>
        public static string Excelente {
            get {
                return ResourceManager.GetString("Excelente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha análisis.
        /// </summary>
        public static string Fechaanálisis {
            get {
                return ResourceManager.GetString("Fechaanálisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Cierre.
        /// </summary>
        public static string FechadeCierre {
            get {
                return ResourceManager.GetString("FechadeCierre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha del análisis.
        /// </summary>
        public static string FechadelAnálisis {
            get {
                return ResourceManager.GetString("FechadelAnálisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Final.
        /// </summary>
        public static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicial.
        /// </summary>
        public static string FechaInicial {
            get {
                return ResourceManager.GetString("FechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks.
        /// </summary>
        public static string Frameworks {
            get {
                return ResourceManager.GetString("Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente.
        /// </summary>
        public static string Gerente {
            get {
                return ResourceManager.GetString("Gerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de errores.
        /// </summary>
        public static string Gestióndeerrores {
            get {
                return ResourceManager.GetString("Gestióndeerrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestión de tareas.
        /// </summary>
        public static string Gestióndetareas {
            get {
                return ResourceManager.GetString("Gestióndetareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado exitoso..
        /// </summary>
        public static string Guardadoexitoso {
            get {
                return ResourceManager.GetString("Guardadoexitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas de trabajo.
        /// </summary>
        public static string Herramientasdetrabajo {
            get {
                return ResourceManager.GetString("Herramientasdetrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historias y Esfuerzo.
        /// </summary>
        public static string HistoriasyEsfuerzo {
            get {
                return ResourceManager.GetString("HistoriasyEsfuerzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitos.
        /// </summary>
        public static string Hitos {
            get {
                return ResourceManager.GetString("Hitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitos de la solución.
        /// </summary>
        public static string Hitosdelasolución {
            get {
                return ResourceManager.GetString("Hitosdelasolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitos de Soluciones.
        /// </summary>
        public static string HitosdeSoluciones {
            get {
                return ResourceManager.GetString("HitosdeSoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUs Estimadas.
        /// </summary>
        public static string HUsEstimadas {
            get {
                return ResourceManager.GetString("HUsEstimadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUs Logradas.
        /// </summary>
        public static string HUsLogradas {
            get {
                return ResourceManager.GetString("HUsLogradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC.
        /// </summary>
        public static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incendios.
        /// </summary>
        public static string Incendios {
            get {
                return ResourceManager.GetString("Incendios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores Técnicos.
        /// </summary>
        public static string IndicadoresTécnicos {
            get {
                return ResourceManager.GetString("IndicadoresTécnicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Cliente.
        /// </summary>
        public static string InformacióndelCliente {
            get {
                return ResourceManager.GetString("InformacióndelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información General.
        /// </summary>
        public static string InformaciónGeneral {
            get {
                return ResourceManager.GetString("InformaciónGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Solución.
        /// </summary>
        public static string InformeSolución {
            get {
                return ResourceManager.GetString("InformeSolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspección continua.
        /// </summary>
        public static string Inspeccióncontinua {
            get {
                return ResourceManager.GetString("Inspeccióncontinua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integración continua.
        /// </summary>
        public static string Integracióncontinua {
            get {
                return ResourceManager.GetString("Integracióncontinua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integraciones Continuas.
        /// </summary>
        public static string Integracionescontinuas {
            get {
                return ResourceManager.GetString("Integracionescontinuas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de consultorías creadas hasta la fecha.
        /// </summary>
        public static string LabelConsultarConsultoriaALaFecha {
            get {
                return ResourceManager.GetString("LabelConsultarConsultoriaALaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo mostrar consultorías en estado ejecución.
        /// </summary>
        public static string LabelMostrarConsultoriasEnEjecucion {
            get {
                return ResourceManager.GetString("LabelMostrarConsultoriasEnEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguaje.
        /// </summary>
        public static string Lenguaj {
            get {
                return ResourceManager.GetString("Lenguaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea.
        /// </summary>
        public static string Linea {
            get {
                return ResourceManager.GetString("Linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea de consultoría.
        /// </summary>
        public static string LineaDeConsultoria {
            get {
                return ResourceManager.GetString("LineaDeConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea de negocio.
        /// </summary>
        public static string Líneadenegocio {
            get {
                return ResourceManager.GetString("Líneadenegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineas de código.
        /// </summary>
        public static string Lineasdecódigo {
            get {
                return ResourceManager.GetString("Lineasdecódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línea tecnológica.
        /// </summary>
        public static string Líneatecnológica {
            get {
                return ResourceManager.GetString("Líneatecnológica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de soluciones creadas hasta la fecha.
        /// </summary>
        public static string Listadodesolucionescreadashastalafecha {
            get {
                return ResourceManager.GetString("Listadodesolucionescreadashastalafecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista proyectos existentes.
        /// </summary>
        public static string ListaProyectosExistentes {
            get {
                return ResourceManager.GetString("ListaProyectosExistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco de trabajo.
        /// </summary>
        public static string Marcodetrabajo {
            get {
                return ResourceManager.GetString("Marcodetrabajo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups. Ocurrió un error inesperado. Contacta al administrador del sistema..
        /// </summary>
        public static string MensajeControlado {
            get {
                return ResourceManager.GetString("MensajeControlado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consultoría ha sido creada.
        /// </summary>
        public static string MensajeCrearConsultoria {
            get {
                return ResourceManager.GetString("MensajeCrearConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sección {0} no pudo ser guardada porque posee campos vacios..
        /// </summary>
        public static string MensajeDatosIncompletos {
            get {
                return ResourceManager.GetString("MensajeDatosIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consultoría ha sido modificada.
        /// </summary>
        public static string MensajeEditarConsultoria {
            get {
                return ResourceManager.GetString("MensajeEditarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consultoria fue eliminada exitosamente.
        /// </summary>
        public static string MensajeEliminadoExitoso {
            get {
                return ResourceManager.GetString("MensajeEliminadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la métrica. Verificar si existe seguimiento registrado..
        /// </summary>
        public static string MensajeEliminarMetrica {
            get {
                return ResourceManager.GetString("MensajeEliminarMetrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la consultoría. Verifique si existe información ingresada.
        /// </summary>
        public static string MensajeErrorEliminarConsultoria {
            get {
                return ResourceManager.GetString("MensajeErrorEliminarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la métrica. Verificar si existe seguimiento registrado..
        /// </summary>
        public static string MensajeErrorEliminarMetricaAgil {
            get {
                return ResourceManager.GetString("MensajeErrorEliminarMetricaAgil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar la solución. Verifique si existe información ingresada.
        /// </summary>
        public static string MensajeErrorEliminarSolucion {
            get {
                return ResourceManager.GetString("MensajeErrorEliminarSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solución fue eliminada exitosamente..
        /// </summary>
        public static string MensajeExitoEliminarSolucion {
            get {
                return ResourceManager.GetString("MensajeExitoEliminarSolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las fechas de los sprint no concuerdan..
        /// </summary>
        public static string MensajeFechaNoConcuerda {
            get {
                return ResourceManager.GetString("MensajeFechaNoConcuerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay sprint o fechas que se encuentran duplicadas..
        /// </summary>
        public static string MensajeFechasDuplicadas {
            get {
                return ResourceManager.GetString("MensajeFechasDuplicadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su registro ha sido agregado.
        /// </summary>
        public static string MensajeRegistroAgregado {
            get {
                return ResourceManager.GetString("MensajeRegistroAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su registro ha sido creado.
        /// </summary>
        public static string MensajeRegistroCreado {
            get {
                return ResourceManager.GetString("MensajeRegistroCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su registro ha sido modificado.
        /// </summary>
        public static string MensajeRegistroModificado {
            get {
                return ResourceManager.GetString("MensajeRegistroModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu solución ha sido agregada.
        /// </summary>
        public static string MensajeSolucionCreada {
            get {
                return ResourceManager.GetString("MensajeSolucionCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu solución ha sido modificada.
        /// </summary>
        public static string MensajeSolucionModificada {
            get {
                return ResourceManager.GetString("MensajeSolucionModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        public static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metricas.
        /// </summary>
        public static string Metricas {
            get {
                return ResourceManager.GetString("Metricas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metricas Agiles.
        /// </summary>
        public static string MetricasAgiles {
            get {
                return ResourceManager.GetString("MetricasAgiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metricas Externas.
        /// </summary>
        public static string MetricasExternas {
            get {
                return ResourceManager.GetString("MetricasExternas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo.
        /// </summary>
        public static string Monitoreo {
            get {
                return ResourceManager.GetString("Monitoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoreo Continuo.
        /// </summary>
        public static string MonitoreoContinuo {
            get {
                return ResourceManager.GetString("MonitoreoContinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aplica Recurso.
        /// </summary>
        public static string NoAplica {
            get {
                return ResourceManager.GetString("NoAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cumple.
        /// </summary>
        public static string NoCumple {
            get {
                return ResourceManager.GetString("NoCumple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre analista.
        /// </summary>
        public static string Nombreanalista {
            get {
                return ResourceManager.GetString("Nombreanalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Compilación.
        /// </summary>
        public static string NombreCompilación {
            get {
                return ResourceManager.GetString("NombreCompilación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del contacto.
        /// </summary>
        public static string Nombredelcontacto {
            get {
                return ResourceManager.GetString("Nombredelcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Despliegue.
        /// </summary>
        public static string NombreDespliegue {
            get {
                return ResourceManager.GetString("NombreDespliegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Inspección.
        /// </summary>
        public static string NombreInspección {
            get {
                return ResourceManager.GetString("NombreInspección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Monitoreo.
        /// </summary>
        public static string NombreMonitoreo {
            get {
                return ResourceManager.GetString("NombreMonitoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre proyecto.
        /// </summary>
        public static string NombreProyecto {
            get {
                return ResourceManager.GetString("NombreProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron registros..
        /// </summary>
        public static string Noseencontraronregistros {
            get {
                return ResourceManager.GetString("Noseencontraronregistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novedades.
        /// </summary>
        public static string Novedades {
            get {
                return ResourceManager.GetString("Novedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Número {
            get {
                return ResourceManager.GetString("Número", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observación.
        /// </summary>
        public static string Observación {
            get {
                return ResourceManager.GetString("Observación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oficina.
        /// </summary>
        public static string Oficina {
            get {
                return ResourceManager.GetString("Oficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origenes de datos.
        /// </summary>
        public static string Origenesdedatos {
            get {
                return ResourceManager.GetString("Origenesdedatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFA.
        /// </summary>
        public static string PFA {
            get {
                return ResourceManager.GetString("PFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataformas.
        /// </summary>
        public static string Plataformas {
            get {
                return ResourceManager.GetString("Plataformas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prácticas de Calidad.
        /// </summary>
        public static string PrácticasdeCalidad {
            get {
                return ResourceManager.GetString("PrácticasdeCalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prácticas Técnicas.
        /// </summary>
        public static string PrácticasTécnicas {
            get {
                return ResourceManager.GetString("PrácticasTécnicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto.
        /// </summary>
        public static string Proyecto {
            get {
                return ResourceManager.GetString("Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto nuevo.
        /// </summary>
        public static string ProyectoNuevo {
            get {
                return ResourceManager.GetString("ProyectoNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas.
        /// </summary>
        public static string Pruebas {
            get {
                return ResourceManager.GetString("Pruebas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas Funcionales.
        /// </summary>
        public static string PruebasFuncionales {
            get {
                return ResourceManager.GetString("PruebasFuncionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas Funcionales Automatizadas.
        /// </summary>
        public static string PruebasFuncionalesAutomatizadas {
            get {
                return ResourceManager.GetString("PruebasFuncionalesAutomatizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas funcionales automatizadas.
        /// </summary>
        public static string PruebasFuncionalesAutomatizadas2 {
            get {
                return ResourceManager.GetString("PruebasFuncionalesAutomatizadas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruebas unitarias automatizadas.
        /// </summary>
        public static string Pruebasunitariasautomatizadas {
            get {
                return ResourceManager.GetString("Pruebasunitariasautomatizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUA.
        /// </summary>
        public static string PUA {
            get {
                return ResourceManager.GetString("PUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Métricas Externas.
        /// </summary>
        public static string RegistrarMétricasExternas {
            get {
                return ResourceManager.GetString("RegistrarMétricasExternas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Métricas Externo.
        /// </summary>
        public static string RegistrarMétricasExterno {
            get {
                return ResourceManager.GetString("RegistrarMétricasExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportados.
        /// </summary>
        public static string Reportados {
            get {
                return ResourceManager.GetString("Reportados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string Reportes {
            get {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable técnico.
        /// </summary>
        public static string Responsabletécnico {
            get {
                return ResourceManager.GetString("Responsabletécnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable Técnico.
        /// </summary>
        public static string Responsabletécnico2 {
            get {
                return ResourceManager.GetString("Responsabletécnico2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No utilice comas en los elementos de esta sección..
        /// </summary>
        public static string RestriccionComa {
            get {
                return ResourceManager.GetString("RestriccionComa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesgos.
        /// </summary>
        public static string Riesgos {
            get {
                return ResourceManager.GetString("Riesgos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Maestro Scrum.
        /// </summary>
        public static string RolScrumMaster {
            get {
                return ResourceManager.GetString("RolScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestro Scrum.
        /// </summary>
        public static string ScrumMaster {
            get {
                return ResourceManager.GetString("ScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimientos.
        /// </summary>
        public static string Seguimientos {
            get {
                return ResourceManager.GetString("Seguimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el idioma.
        /// </summary>
        public static string Seleccioneelidioma {
            get {
                return ResourceManager.GetString("Seleccioneelidioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al procesar su solicitud..
        /// </summary>
        public static string Seprodujounerroralprocesarsusolicitud {
            get {
                return ResourceManager.GetString("Seprodujounerroralprocesarsusolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharepoint.
        /// </summary>
        public static string Sharepoint {
            get {
                return ResourceManager.GetString("Sharepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo mostrar proyectos en estado ejecución.
        /// </summary>
        public static string Solomostrarproyectosenestadoejecución {
            get {
                return ResourceManager.GetString("Solomostrarproyectosenestadoejecución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solución.
        /// </summary>
        public static string Solucion {
            get {
                return ResourceManager.GetString("Solucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solucionados.
        /// </summary>
        public static string Solucionados {
            get {
                return ResourceManager.GetString("Solucionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soluciones.
        /// </summary>
        public static string Soluciones {
            get {
                return ResourceManager.GetString("Soluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        public static string Sprint {
            get {
                return ResourceManager.GetString("Sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero de Prácticas Técnicas.
        /// </summary>
        public static string TablerodePrácticasTécnicas {
            get {
                return ResourceManager.GetString("TablerodePrácticasTécnicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableros.
        /// </summary>
        public static string Tableros {
            get {
                return ResourceManager.GetString("Tableros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tareas / Errores.
        /// </summary>
        public static string TareasErrores {
            get {
                return ResourceManager.GetString("TareasErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnico.
        /// </summary>
        public static string Tecnico {
            get {
                return ResourceManager.GetString("Tecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnología.
        /// </summary>
        public static string Tecnología {
            get {
                return ResourceManager.GetString("Tecnología", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologías.
        /// </summary>
        public static string Tecnologías {
            get {
                return ResourceManager.GetString("Tecnologías", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Teléfono {
            get {
                return ResourceManager.GetString("Teléfono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipificación.
        /// </summary>
        public static string Tipificación {
            get {
                return ResourceManager.GetString("Tipificación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Consultorías.
        /// </summary>
        public static string TituloAdministrarConsultoria {
            get {
                return ResourceManager.GetString("TituloAdministrarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Consultoría.
        /// </summary>
        public static string TituloAgregarConsultoria {
            get {
                return ResourceManager.GetString("TituloAgregarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Consultoría.
        /// </summary>
        public static string TituloEditarConsultoria {
            get {
                return ResourceManager.GetString("TituloEditarConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Consultoría.
        /// </summary>
        public static string TituloVistaPreviaConsultoria {
            get {
                return ResourceManager.GetString("TituloVistaPreviaConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu registro ha sido.
        /// </summary>
        public static string Turegistrohasido {
            get {
                return ResourceManager.GetString("Turegistrohasido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu solución ha sido.
        /// </summary>
        public static string Tusoluciónhasido {
            get {
                return ResourceManager.GetString("Tusoluciónhasido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Compilacion.
        /// </summary>
        public static string UrlCompilacion {
            get {
                return ResourceManager.GetString("UrlCompilacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Despliegue.
        /// </summary>
        public static string UrlDespliegue {
            get {
                return ResourceManager.GetString("UrlDespliegue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url diseño de casos.
        /// </summary>
        public static string UrlDiseñodeCasos {
            get {
                return ResourceManager.GetString("UrlDiseñodeCasos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url documentación.
        /// </summary>
        public static string Urldocumentación {
            get {
                return ResourceManager.GetString("Urldocumentación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Evidencia Completado.
        /// </summary>
        public static string UrlEvidenciaCompletado {
            get {
                return ResourceManager.GetString("UrlEvidenciaCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url evidencias.
        /// </summary>
        public static string UrlEvidencias {
            get {
                return ResourceManager.GetString("UrlEvidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url inspección.
        /// </summary>
        public static string Urlinspección {
            get {
                return ResourceManager.GetString("Urlinspección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Monitoreo.
        /// </summary>
        public static string UrlMonitoreo {
            get {
                return ResourceManager.GetString("UrlMonitoreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url repositorio.
        /// </summary>
        public static string UrlRepositorio {
            get {
                return ResourceManager.GetString("UrlRepositorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url repositorio codigo fuente.
        /// </summary>
        public static string Urlrepositoriocodigofuente {
            get {
                return ResourceManager.GetString("Urlrepositoriocodigofuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de red del consultor.
        /// </summary>
        public static string UsuarioDeRedConsultor {
            get {
                return ResourceManager.GetString("UsuarioDeRedConsultor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de red del gerente.
        /// </summary>
        public static string UsuariodereddelGerente {
            get {
                return ResourceManager.GetString("UsuariodereddelGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de red del Responsable.
        /// </summary>
        public static string UsuariodereddelResponsable {
            get {
                return ResourceManager.GetString("UsuariodereddelResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de red del Maestro Scrum.
        /// </summary>
        public static string UsuariodereddelScrumMaster {
            get {
                return ResourceManager.GetString("UsuariodereddelScrumMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario red analista.
        /// </summary>
        public static string Usuarioredanalista {
            get {
                return ResourceManager.GetString("Usuarioredanalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilitarios.
        /// </summary>
        public static string Utilitarios {
            get {
                return ResourceManager.GetString("Utilitarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UX.
        /// </summary>
        public static string UX {
            get {
                return ResourceManager.GetString("UX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string VerDetalle {
            get {
                return ResourceManager.GetString("VerDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Resumen Solución.
        /// </summary>
        public static string VerResumenSolución {
            get {
                return ResourceManager.GetString("VerResumenSolución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista Previa.
        /// </summary>
        public static string VistaPrevia {
            get {
                return ResourceManager.GetString("VistaPrevia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulnerabilidades.
        /// </summary>
        public static string Vulnerabilidades {
            get {
                return ResourceManager.GetString("Vulnerabilidades", resourceCulture);
            }
        }
    }
}

